const themeLink=document.createElement('link');themeLink.rel='stylesheet';themeLink.href='theme.css?v=20260908-5';document.head.appendChild(themeLink);
const fixesLink=document.createElement('link');fixesLink.rel='stylesheet';fixesLink.href='site-fixes.css?v=20260914-social-1';document.head.appendChild(fixesLink);const ruStyle=document.createElement('link');ruStyle.rel='stylesheet';ruStyle.href='site-ru.css?v=20260920-prod1';document.head.appendChild(ruStyle);
const fontLink=document.createElement('link');fontLink.rel='stylesheet';fontLink.href='https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600;700;800;900&family=Rubik:wght@500;600;700;800;900&display=swap';document.head.appendChild(fontLink);
const PRIMARY_PHONE_DISPLAY='08-6335333';const PRIMARY_PHONE_HREF='086335333';const LOGO='https://media.easy.co.il/images/UserThumbs/10143668_1752242943315_0.png';
function normalizePhones(){const re=/(?:054[\s-]*909[\s-]*1504|050[\s-]*742[\s-]*6263|08[\s-]*633[\s-]*5333)/g;document.querySelectorAll('a[href^="tel:"]').forEach(a=>{a.href='tel:'+PRIMARY_PHONE_HREF;a.textContent=PRIMARY_PHONE_DISPLAY;a.setAttribute('dir','ltr');a.classList.add('phone-ltr')});const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);nodes.forEach(n=>{const p=n.parentElement;if(!p||p.closest('a[href^="tel:"]')||['SCRIPT','STYLE'].includes(p.tagName))return;const text=n.nodeValue;re.lastIndex=0;if(!re.test(text))return;re.lastIndex=0;const frag=document.createDocumentFragment();let last=0;for(const m of text.matchAll(re)){frag.append(document.createTextNode(text.slice(last,m.index)));const bdi=document.createElement('bdi');bdi.className='phone-ltr';bdi.dir='ltr';bdi.textContent=PRIMARY_PHONE_DISPLAY;frag.append(bdi);last=m.index+m[0].length}frag.append(document.createTextNode(text.slice(last)));n.replaceWith(frag)})}
function normalizeBrand(){document.querySelectorAll('.nav .brand').forEach(brand=>{if(!brand.querySelector('img')){const img=document.createElement('img');img.src=LOGO;img.alt='Логотип Центра «Эден»';brand.prepend(img)}if(!brand.querySelector('strong')){const s=document.createElement('strong');s.textContent='Центр «Эден»';brand.appendChild(s)}});document.querySelectorAll('.menu a[href*="eden-baby"]').forEach(a=>a.textContent='Плавание для младенцев');document.querySelectorAll('.menu a').forEach(a=>{const here=location.pathname.split('/').pop()||'index-ru.html';const there=a.getAttribute('href').split('/').pop();if(here===there)a.classList.add('active')})}
function improveHeroCard(){const quick=document.querySelector('.heroCard .quick');if(quick){quick.innerHTML='<a href="team-ru.html">Профессиональная и опытная команда</a><a href="pools-ru.html">Качественные бассейны и постоянный контроль</a><a href="about-ru.html">Индивидуальное сопровождение и непрерывность терапии</a>'}document.querySelectorAll('.crm').forEach(el=>{const section=el.closest('section');if(section)section.remove();else el.remove()})}
function addWelcomeThought(){const file=location.pathname.split('/').pop()||'index-ru.html';if(file!=='index-ru.html'&&file!=='')return;const actions=document.querySelector('.heroCopy .actions');if(!actions||document.querySelector('.welcomeThought'))return;const thoughts=['Иногда самый большой шаг начинается с маленькой капли','У каждого ребёнка свой темп — мы здесь, чтобы сопровождать его.','Каждый маленький шаг — это целый мир','Настоящие перемены начинаются там, где тебя действительно понимают.','В Центре «Эден» в первую очередь видят человека, а не его трудности.','Иногда всё, что нужно — поддерживающая среда и человек, который верит в тебя.','Вода, доверие, терпение — так начинается путь','Каждому ребёнку нужно место, где верят в его способности','Путь к прогрессу начинается с чувства уверенности','Мы не торопим процесс, мы сопровождаем его','Профессиональное место может ощущаться как дом','В воде проявляются возможности, которые не всегда видны на суше.','Каждая семья заслуживает чувствовать, что рядом есть кто‑то, кто идёт с ней по этому пути.','Иногда первая улыбка в воде говорит больше, чем тысяча слов.','Не все пути выглядят одинаково — в этом и заключается их красота.','В Центре «Эден» каждый человек получает своё место, своё время и свой путь'];let previous=-1;try{previous=Number(sessionStorage.getItem('edenThoughtIndex')??-1)}catch(e){}let index=Math.floor(Math.random()*thoughts.length);if(thoughts.length>1&&index===previous)index=(index+1)%thoughts.length;try{sessionStorage.setItem('edenThoughtIndex',String(index))}catch(e){}const el=document.createElement('div');el.className='welcomeThought';el.setAttribute('aria-live','polite');el.innerHTML='<span class="welcomeSpark">✦</span><span>'+thoughts[index]+'</span><span class="welcomeSpark">✦</span>';actions.insertAdjacentElement('afterend',el)}
function addWhyEden(){const file=location.pathname.split('/').pop()||'index-ru.html';if(['index-ru.html','','contact-ru.html','privacy-ru.html','accessibility-ru.html','terms-ru.html','reviews-ru.html'].includes(file)||document.querySelector('.whyEden'))return;const map={
'about-ru.html':['Почему семьи выбирают Центр «Эден»','Особенность Центра «Эден» — сочетание профессиональной водной среды, команды, которая знает человека, а не только терапию, индивидуальной адаптации и обеспечения чёткой преемственности на протяжении всего пути.',['Индивидуальный подход, а не универсальная схема','Специальные бассейны и тщательно организованная среда','Профессиональная команда и семейное отношение']],
'services-ru.html':['Не просто разнообразие направлений терапии — а правильный подбор','Мы не начинаем с названия направления терапии, а с потребности. Цель — подобрать вид активности, темп и формат так, чтобы они соответствовали человеку, который приходит к нам.',['Подбор в зависимости от возраста и возможностей','Небольшие группы и индивидуальный подход','Преемственность между направлениями терапии и видами деятельности']],
'hydrotherapy-children-ru.html':['Преимущество Центра «Эден» для детей','Работа сочетает профессионализм с тёплой, не пугающей атмосферой. Ребёнок развивается в своём темпе, а команда стремится выстраивать уверенность, контакт и ощущения успеха.',['Индивидуальный темп','Знакомая и спокойная обстановка','Вовлечение родителей по мере необходимости']],
'hydrotherapy-adults-ru.html':['Вода, движение и индивидуальный подход','В Центре «Эден» для взрослого нет единой программы. Занятия формируются в соответствии со способностями, ощущениями и личной целью, в спокойной контролируемой обстановке.',['Индивидуальная нагрузка','Индивидуальное внимание','Тёплые и приятные бассейны']],
'therapeutic-swimming-ru.html':['Учиться и развиваться без давления','Лечебное плавание в Центре «Эден» сочетает обучение водным навыкам с личным подходом, учитывающим темп, уверенность и возможности.',['Постепенный прогресс','Укрепление уверенности в воде','Индивидуальное профессиональное сопровождение']],
'eden-baby-ru.html':['Что особенного в плавании для младенцев Eden Baby?','Занятие выстроено как совместный опыт родителя и младенца. Акцент на установлении связи, приятном знакомстве с водой, движении, игре и ощущении безопасности. Занятия проходят в небольших группах и тёплой атмосфере.',['Родитель и младенец вместе','Небольшая группа и личное внимание','Постепенное знакомство с водой']],
'pools-ru.html':['Бассейн — важная часть качества услуг','В Центре «Эден» водная среда — неотъемлемая часть сервиса. Мы строго следим за регулярным обслуживанием, чистотой, контролем и качеством воды в соответствии с указаниями Министерства здравоохранения Израиля и соответствующими требованиями.',['Качество воды и контроль','Регулярное техническое обслуживание','Приспособленная среда для занятий']],
'team-ru.html':['Команда, знающая человека, стоящего за терапией.','Профессионализм важен, но не менее важны контакт и доверие. Команда Центра «Эден» работает с вниманием, терпением, индивидуальным подходом и в сотрудничестве с вами, чтобы создать последовательный и комфортный процесс.',['Профессиональное обучение','Практический опыт','Индивидуальный и семейный подход']],
'autism-ru.html':['Особенность Центра «Эден» — индивидуальная адаптация для людей в аутистическом спектре','Нет единого шаблона, подходящего всем. Мы подбираем темп, окружающую среду, способ знакомства с водой и формат занятий для каждого — для ребёнка, подростка или взрослого.',['Индивидуальный темп','Максимально привычная среда','Преемственность и вовлечение семьи']],
'knowledge-ru.html':['Информация, помогающая семьям понять и сделать выбор','Информационный центр создан, чтобы дать понятные разъяснения перед принятием решения. Мы убеждены, что семья, понимающая процесс, сможет выбрать более обдуманно и прийти спокойнее.',['Понятный профессиональный контент','Вопросы, которые родители действительно задают','Прямая ссылка на страницы терапии']]
};const data=map[file];if(!data)return;const [title,text,items]=data;const section=document.createElement('section');section.className='section alt whyEden';section.innerHTML=`<div class="container"><h2 class="title center">${title}</h2><p class="lead center">${text}</p><div class="featureGrid">${items.map(i=>`<div class="feature"><strong>${i}</strong><span>Это часть подхода Центра «Эден», где в центре внимания — человек, его безопасность и индивидуальная адаптация.</span></div>`).join('')}</div><p class="center" style="margin-top:1.2rem"><a class="btn light" href="contact-ru.html">Записаться на консультацию по подбору программы в Центр «Эден»</a></p></div>`;const footer=document.querySelector('footer');if(footer)footer.before(section)}
normalizePhones();normalizeBrand();improveHeroCard();addWelcomeThought();addWhyEden();
const menuBtn=document.querySelector('.mobileBtn');const menu=document.querySelector('.menu');if(menuBtn&&menu){menuBtn.addEventListener('click',()=>{menu.classList.toggle('open');menuBtn.setAttribute('aria-expanded',menu.classList.contains('open'))});menu.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{menu.classList.remove('open');menuBtn.setAttribute('aria-expanded','false')}))}
const form=document.querySelector('[data-lead-form]');if(form){form.addEventListener('submit',async e=>{e.preventDefault();const msg=form.querySelector('.formMsg');const btn=form.querySelector('button[type=submit]');const data=Object.fromEntries(new FormData(form).entries());data.source='website-v2';data.sourcePage=location.href;data.fullName=data.childName||data.fullName||data.parentName;msg.className='formMsg';msg.textContent='';btn.disabled=true;btn.textContent='Отправляем запрос...';try{const r=await fetch('https://eden-center-crm.onrender.com/api/public/leads',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});if(!r.ok)throw new Error('http');msg.className='formMsg ok';msg.textContent='Спасибо! Запрос успешно получен. Команда Центра «Эден» свяжется с вами в ближайшее время.';form.reset()}catch(err){msg.className='formMsg bad';msg.innerHTML='Сейчас не удалось отправить обращение. Можно позвонить в Центр по номеру <bdi class="phone-ltr" dir="ltr">'+PRIMARY_PHONE_DISPLAY+'</bdi>.'}finally{btn.disabled=false;btn.textContent='Отправить запрос в Центр «Эден»'}})}
// cooking-baking-nav
(function addCookingBakingNav(){
  document.querySelectorAll('.menu').forEach(menu=>{
    if(menu.querySelector('a[href="cooking-baking-ru.html"]')) return;
    const a=document.createElement('a');
    a.href='cooking-baking-ru.html';
    a.textContent='Кулинария и выпечка';
    const services=menu.querySelector('a[href="services-ru.html"]');
    if(services) services.insertAdjacentElement('afterend',a); else menu.appendChild(a);
    const here=location.pathname.split('/').pop()||'index-ru.html';
    if(here==='cooking-baking-ru.html') a.classList.add('active');
  });
})();


/* Social shortcuts in the white header area. Kept separate from the main menu. */
(function addSocialHeaderButtons(){
  const navrow=document.querySelector('.navrow');
  const brand=navrow&&navrow.querySelector('.brand');
  if(!navrow||!brand||navrow.querySelector('.edenSocialLinks'))return;
  const links=document.createElement('div');
  links.className='edenSocialLinks';
  links.setAttribute('aria-label','Центр «Эден» в социальных сетях');
  links.innerHTML=`
    <a class="edenSocialButton edenInstagram" href="https://www.instagram.com/eden_life_skils/" target="_blank" rel="noopener noreferrer" aria-label="Центр «Эден» в Инстаграме" title="Инстаграм">
      <svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5"></rect><circle cx="12" cy="12" r="4.25"></circle><circle class="socialDot" cx="17.4" cy="6.7" r="1.15"></circle></svg>
    </a>
    <a class="edenSocialButton edenFacebook" href="https://www.facebook.com/profile.php?id=100063968114891" target="_blank" rel="noopener noreferrer" aria-label="Центр «Эден» в Фейсбуке" title="Фейсбук">
      <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M13.65 21v-8h2.75l.42-3.12h-3.17v-2c0-.91.26-1.52 1.59-1.52h1.7V3.57c-.3-.04-1.3-.12-2.48-.12-2.45 0-4.13 1.48-4.13 4.21v2.22H8.55V13h2.78v8h2.32Z"></path></svg>
    </a>`;
  brand.insertAdjacentElement('afterend',links);
})();
